# Use an official Node runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json AND package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Build the app
RUN npm run build


# Make port 3000 available to the world outside this container
ARG PORT=3001
ENV PORT $PORT
EXPOSE $PORT

ARG NEXT_PUBLIC_SERVER_URL=https://server-ey6altycha-wl.a.run.app
ENV NEXT_PUBLIC_SERVER_URL $NEXT_PUBLIC_SERVER_URL

# Run serve when the container launches
CMD npm start -p 


