# Use an official Node runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json AND package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY . .

# Build the app
RUN npm run build


# Make port 3000 available to the world outside this container
ARG PORT=3000
ENV PORT $PORT
EXPOSE $PORT

# Run serve when the container launches
CMD ["npm", "start"]

