runtime: python312
env: flex

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker myapp:app

env_variables:
  # Environment variables can be set here
  SECRET_KEY: "your-secret-key"
  ANOTHER_ENV_VAR: "another-value"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

handlers:
  # Serve static files directly from Google App Engine
  - url: /static
    static_dir: static/

  # All other URLs should be handled by the application itself
  - url: /.*
    script: auto

# Optional: Custom network settings
network:
  instance_tag: my-fastapi-app
  name: default

