version: '3'
services:
  fastapi:
    build: ./server  # Ensure this is the correct path to your FastAPI app
    ports:
      - "8000:8000"  # Expose FastAPI on port 5001
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    # Note: Replace 'server:app' with the actual Python module and FastAPI app instance names
    # The --reload flag is used for development and automatically reloads the server on code changes

  nextjs:
    build: ./client  # Ensure this is the correct path to your Next.js app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://fastapi:8000
      # Use NEXT_PUBLIC_ prefix for env vars to expose them to the browser in Next.js
    depends_on:
      - fastapi
