apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: nextjs
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nextjs
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/nc-default: "true"
        io.kompose.service: nextjs
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_SERVER_URL
              value: http://fastapi:8080
          image: us-west2-docker.pkg.dev/neuralcloak-415702/neuralcloak/test_client:test
          name: nextjs
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
